nelmio_api_doc:
    documentation:
        info:
            title: Log analytics API
            version: 1.0.0
            description: Log stream analysis API
            contact:
                email: dumetskiy@gmail.com
        tags:
            - name: analytics
              description: Analytics functions
    areas:
        path_patterns:
            - ^/(?!api/doc|_error|$)
