version: '3.7'

services:
  web:
    container_name: parser.web
    build:
      context: docker/web/
    restart: on-failure
    ports:
      - ${WEB_API_PORT:-8899}:80
    volumes:
      - ./public:/app/public
    env_file:
      - .env
    depends_on:
      - php
    networks:
      - parser-network

  php:
    container_name: parser.php-fpm
    build:
      context: docker/php-fpm/
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - parser-network

  elasticsearch:
    container_name: parser.elasticsearch
    build:
      context: docker/elasticsearch/
      args:
        STACK_VERSION: $STACK_VERSION
    volumes:
      - type: bind
        source: ./docker/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT:-9200}:9200
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: ${LICENSE}
    env_file:
      - .env
    networks:
      - parser-network

  logstash:
    container_name: parser.logstash
    build:
      context: docker/logstash/
      args:
        STACK_VERSION: $STACK_VERSION
    volumes:
      - type: bind
        source: ./docker/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./docker/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - ${LOGSTASH_PORT:-5010}:5010
    env_file:
      - .env
    networks:
      - parser-network
    depends_on:
      - elasticsearch

  kibana:
    container_name: parser.kibana
    build:
      context: docker/kibana/
      args:
        STACK_VERSION: $STACK_VERSION
    volumes:
      - type: bind
        source: ./docker/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - ${KIBANA_PORT:-5601}:5601
    env_file:
      - .env
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:${ELASTIC_PORT:-9200}"]'
    networks:
      - parser-network
    depends_on:
      - elasticsearch

networks:
  parser-network:
    driver: bridge

volumes:
  elasticsearch: