parameters:
    log_parser.configuration.parsing.batch_size: 2
    log_parser.configuration.filesystem.logs_directory: data

    log_parser.logstash.address: '%env(string:LOGSTASH_ADDRESS)%'
    log_parser.elastic.address: '%env(string:ELASTIC_ADDRESS)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        LogParser\Handler\LogProcessing\LogProcessingHandlerInterface:
            tags: ['log_parser.processing.handler']

    LogParser\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    log_parser.configuration:
        class: LogParser\ValueObject\ParserConfiguration
        arguments:
            $logsDirectory: '%log_parser.configuration.filesystem.logs_directory%'
            $batchSize: '%log_parser.configuration.parsing.batch_size%'