parameters:
    log_parser.configuration.parsing.batch_size: 1000
    log_parser.configuration.filesystem.logs_directory: data
services:
    _defaults:
        autowire: true
        autoconfigure: true

    LogParser\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    log_parser.configuration:
        class: LogParser\ValueObject\ParserConfiguration
        arguments:
            $logsDirectory: '%log_parser.configuration.filesystem.logs_directory%'
            $batchSize: '%log_parser.configuration.parsing.batch_size%'