indexes:
  logs:
    settings:
      number_of_shards: 1
    mappings:
      properties:
        date_time:
          type: date
          format: dd/MMM/yyyy:HH:mm:ss Z
        http_code:
          type: short
        service_name:
          type: keyword
